# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f38a65a8ca15f0cb96d63bd07715bf7689609f6b743ce4d8205389e87be00ec3d6db76ea088cc1b06485b7246e275c18cc3abb9bb6073055b3f4c968ccc8609a

test:
  secret_key_base: 392dfce36e5031995cf3e86755afcb8fc5163dc984f9a42804577e081232bf39be125188f773b3e72eac4987d459cff4156074ac7a0c5ecc544385010db4d067

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
